apiVersion: v1
kind: Service
metadata:
  name: {{ include "procworks.api.fullname" . }}
  labels:
    {{- include "procworks.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "procworks.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
