{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "procworks.database.secretName" . }}
  labels:
    {{- include "procworks.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url | quote }}
{{- end }}
