apiVersion: v1
kind: Service
metadata:
  name: {{ include "procworks.web.fullname" . }}
  labels:
    {{- include "procworks.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "procworks.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.port }}
      targetPort: http
